
export const FETCH_RECTANGLES_REQUEST = 'FETCH_RECTANGLES_REQUEST'
export const FETCH_RECTANGLES_SUCCESS = 'FETCH_RECTANGLES_SUCCESS'
export const FETCH_RECTANGLES_FAILURE = 'FETCH_RECTANGLES_FAILURE'

export const CREATE_RECTANGLE_REQUEST = 'CREATE_RECTANGLE_REQUEST'
export const CREATE_RECTANGLE_SUCCESS = 'CREATE_RECTANGLE_SUCCESS'
export const CREATE_RECTANGLE_FAILURE = 'CREATE_RECTANGLE_FAILURE'



export interface RectangleT {
  x0: number,
  y0: number,
  x1: number,
  y1: number,
  r?: number,
  g?: number,
  b?: number
}

export default {
  FETCH_RECTANGLES_REQUEST,
  FETCH_RECTANGLES_SUCCESS,
  FETCH_RECTANGLES_FAILURE,
  CREATE_RECTANGLE_REQUEST,
  CREATE_RECTANGLE_SUCCESS,
  CREATE_RECTANGLE_FAILURE,
}
